package com.segroup2.progettosegroup2.Triggers;

public enum TriggerEnum {
    TRIGGER_TIME_OF_DAY,
    TRIGGER_DAY_OF_MONTH,
    TRIGGER_DAY_OF_WEEK,
    TRIGGER_DATE,
    TRIGGER_FILE_EXISTS,
    TRIGGER_FILE_SIZE,
    TRIGGER_COMPARE_COUNTER_AND_VALUE,
    TRIGGER_COMPARE_COUNTERS
}
